# Generated by Django 5.2.1 on 2025-07-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('copyright', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('copy', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
