# Generated by Django 5.2.1 on 2025-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
