# Generated by Django 5.2.1 on 2025-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('NONFICTION', 'Non-fiction'), ('SCIENCE', 'Science'), ('HISTORY', 'History'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.CharField(choices=[('2024-2025 1st semester', '2024-2025 1st semester'), ('2024-2025 2nd semester', '2024-2025 2nd semester'), ('2025-2026 1st semester', '2025-2026 1st semester')], default='2024-2025 1st semester', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSIS', 'BSIS')], max_length=10),
        ),
    ]
