# Generated by Django 5.2.1 on 2025-07-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book_bookshelf_enrollment_school_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
