# Generated by Django 5.2.1 on 2025-07-22 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_enrollment_student_user_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Precomputed sentence embedding for semantic search.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1')], default='A1', max_length=50),
        ),
    ]
