# Generated by Django 5.2.1 on 2025-07-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_book_embedding_alter_book_bookshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copyright',
            field=models.IntegerField(null=True),
        ),
    ]
