# Generated by Django 5.2.1 on 2025-08-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_book_author_alter_book_copy_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, choices=[('AB-Theology', 'AB-Theology'), ('Master of Divinity programs', 'Master of Divinity programs')], max_length=255),
        ),
    ]
