# Generated by Django 5.2.1 on 2025-09-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
