# Generated by Django 5.2.1 on 2025-09-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_book_author_alter_book_isbn_alter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchoolYear',
            fields=[
                ('school_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'course_school_years',
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='school_year',
        ),
        migrations.AddField(
            model_name='course',
            name='school_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.courseschoolyear'),
        ),
    ]
