# Generated by Django 5.2.1 on 2025-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_courseschoolyear_remove_enrollment_school_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='content_files/'),
        ),
    ]
