# Generated by Django 5.2.1 on 2025-10-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_content_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='file_path',
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.content')),
            ],
            options={
                'db_table': 'content_files',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submission_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='api.grade')),
            ],
            options={
                'db_table': 'submission_files',
            },
        ),
    ]
