# Generated by Django 5.2.1 on 2025-10-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_content_file_path_remove_grade_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Late', 'Late')], max_length=20),
        ),
    ]
