# Generated by Django 5.2.1 on 2025-11-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_grade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
