# Generated by Django 5.2.1 on 2025-11-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_content_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='total_score',
        ),
        migrations.AddField(
            model_name='grade',
            name='normalized_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
