# Generated by Django 5.2.1 on 2025-11-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_grade_total_score_grade_normalized_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_active',
        ),
    ]
