# Generated by Django 5.2.1 on 2025-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_content_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
