# Generated by Django 5.2.1 on 2025-11-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_grade_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendedBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
            options={
                'db_table': 'course_recommended_books',
                'unique_together': {('course', 'book')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_books',
            field=models.ManyToManyField(blank=True, related_name='recommended_in_courses', through='api.CourseRecommendedBook', to='api.book'),
        ),
    ]
