# Generated by Django 5.2.1 on 2025-11-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_courserecommendedbook_course_recommended_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='search_count',
            new_name='recommendation_count',
        ),
    ]
