# Generated by Django 5.2.1 on 2025-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_search_count_book_recommendation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
    ]
