# Generated by Django 5.2.1 on 2025-11-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_book_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'student_logs',
            },
        ),
    ]
