# Generated by Django 5.2.1 on 2025-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_instructorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'school_year')},
        ),
    ]
