# Generated by Django 5.2.1 on 2025-11-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='api.courseschoolyear'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
    ]
