# Generated by Django 5.2.1 on 2025-11-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_course_school_year_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
