# Generated by Django 5.2.1 on 2025-11-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_enrollment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
