# Generated by Django 5.2.1 on 2025-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_user_profile_picture_url_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Administrator', 'Administrator'), ('Librarian', 'Librarian')], max_length=20),
        ),
    ]
