# Generated by Django 5.2.1 on 2025-11-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='section',
        ),
    ]
