# Generated by Django 5.2.1 on 2025-11-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_notification_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('bookshelf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'bookshelves',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.bookshelf'),
        ),
    ]
