# Generated by Django 5.2.1 on 2025-11-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_bookshelf_alter_book_bookshelf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'school_year', 'instructor')},
        ),
    ]
