# Generated by Django 5.2.1 on 2025-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('Activity', 'Activity'), ('File', 'File'), ('Announcement', 'Announcement')], max_length=20),
        ),
    ]
