# Generated by Django 5.2.1 on 2026-01-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_bookrequest_borrowrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='status',
        ),
    ]
