# Generated by Django 5.2.1 on 2026-01-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_bookrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='book_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
