# Generated by Django 5.2.1 on 2026-01-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_borrowrecord_book_condition_borrowrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='book_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent - Like new'), ('good', 'Good - Normal wear'), ('fair', 'Fair - Noticeable wear'), ('poor', 'Poor - Damaged')], max_length=20, null=True),
        ),
    ]
