# Generated by Django 5.2.1 on 2026-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_borrowrecord_book_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Needs Action', 'Needs Action')], default='Pending', max_length=20),
        ),
    ]
