# Generated by Django 5.2.1 on 2026-02-08 07:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_bookrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='ebooks/'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='content_files/'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submission_files/'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
