# Generated by hand to restore environment-aware storage

from django.db import migrations, models
from django.core.files.storage import storages

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_book_copy_alter_book_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.FileField(blank=True, null=True, storage=storages["raw"], upload_to='ebooks/'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(storage=storages["raw"], upload_to='content_files/'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=storages["raw"], upload_to='submission_files/'),
        ),
    ]
