# Generated by Django 5.2.1 on 2026-05-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_restore_environment_aware_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Administrator', 'Administrator'), ('Librarian', 'Librarian'), ('Accounting', 'Accounting'), ('Superadmin', 'Superadmin')], max_length=20),
        ),
    ]
