# Generated by Django 5.2.1 on 2026-03-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingFee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounting_fees',
            },
        ),
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='api.user')),
            ],
            options={
                'db_table': 'student_balances',
            },
        ),
        migrations.CreateModel(
            name='StudentTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Charge', 'Charge'), ('Payment', 'Payment')], max_length=10)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to='api.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.user')),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to='api.user')),
            ],
            options={
                'db_table': 'student_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
