# Generated by Django 5.2.1 on 2026-03-31 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_accountingfee_studentbalance_studenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransaction',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TransactionAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_to', to='api.studenttransaction')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_from', to='api.studenttransaction')),
            ],
            options={
                'db_table': 'student_transaction_allocations',
            },
        ),
    ]
