# Generated by Django 5.2.1 on 2026-04-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_studenttransaction_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='source_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations_provided', to='api.studenttransaction'),
        ),
    ]
