# Generated by Django 5.2.1 on 2026-05-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_courseschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('download_id', models.AutoField(primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api.user')),
            ],
            options={
                'db_table': 'file_downloads',
                'unique_together': {('content', 'user')},
            },
        ),
    ]
