# Generated by Django 5.2.1 on 2026-05-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_filedownload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'course_title', 'school_year', 'instructor')},
        ),
    ]
