# Generated by Django 5.2.1 on 2026-05-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'school_year', 'instructor')},
        ),
        migrations.CreateModel(
            name='BookAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_accesses', to='api.user')),
            ],
            options={
                'db_table': 'book_accesses',
            },
        ),
    ]
