"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = "RENDER" not in os.environ

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",  # Allows all Render subdomains
]

if "BACKEND_URL" in os.environ:
    # Extract host from URL if provided (e.g., https://api.example.com -> api.example.com)
    from urllib.parse import urlparse
    backend_host = urlparse(os.environ["BACKEND_URL"]).hostname
    if backend_host:
        ALLOWED_HOSTS.append(backend_host)


# Application definition
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary_storage",
    "cloudinary",
    "rest_framework",
    "corsheaders",
    "api",
]

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "500/minute",   # Increased to prevent shared IP/NAT blockages in school labs
        "user": "2000/hour",    # Generous limit for logged-in users
        "login": "10/minute",   # Strict limit for login attempts
        "register": "10/minute",
        "password_reset": "10/minute",
    },
}

import sys
IS_TESTING = "test" in sys.argv

if IS_TESTING:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []
    # Disable throttling during tests (using a new dict to avoid type inference issues)
    test_rates: dict = {
        "anon": None,
        "user": None,
        "login": None,
        "register": None,
        "password_reset": None,
    }
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = test_rates

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "api.middleware.ActiveUserMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
CSRF_COOKIE_SECURE = not DEBUG

X_FRAME_OPTIONS = "SAMEORIGIN"

# Session Settings
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds (middleware handles 30m timeout)
SESSION_SAVE_EVERY_REQUEST = True  # Reset session timer on every request

CORS_ALLOW_CREDENTIALS = True


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
]

if "FRONTEND_URL" in os.environ:
    # Normalize URL: strip trailing slashes for consistency
    frontend_url = os.environ["FRONTEND_URL"].rstrip("/")
    if frontend_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(frontend_url)
    if frontend_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(frontend_url)

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Get DATABASE_URL from environment
database_url = os.environ.get("DATABASE_URL", "").strip()

if not database_url:
    raise ValueError(
        "DATABASE_URL environment variable is not set or is empty. "
        "Please add it in Render Dashboard > Environment > Environment Variables"
    )

# Normalize database URL to always use 'postgresql://' scheme (essential for SQLAlchemy and some drivers)
if database_url.startswith("postgres://"):
    database_url = database_url.replace("postgres://", "postgresql://", 1)

if not database_url.startswith("postgresql://"):
    # Truncate for the error message (using a simple slicing pattern)
    trunc: str = database_url[:20]
    raise ValueError(
        f"DATABASE_URL has invalid format. Must start with 'postgresql://' or 'postgres://'. "
        f"Current value starts with: {trunc}..."
    )

# Parse the database URL
parsed_config = dj_database_url.parse(database_url)

if not parsed_config.get("NAME"):
    raise ValueError(
        f"DATABASE_URL parsing failed - no database NAME found. "
        f"URL format: {database_url.split('@')[0]}@... "
        f"Parsed config: {parsed_config}"
    )

DATABASES = {
    "default": {
        **parsed_config,
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
    }
}

if "supabase" in database_url:
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "require",
    }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files (Uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
    "SECURE": True,
}

# Google Drive API (used for document storage: PDFs, Word docs, ebooks, submissions)
GOOGLE_DRIVE_FOLDER_ID = os.environ.get("GOOGLE_DRIVE_FOLDER_ID", "")

# Initialize the cloudinary SDK so that cloudinary.utils.cloudinary_url()
# can generate correct signed URLs for raw file delivery.
# django-cloudinary-storage only configures its own storage backends;
# the underlying cloudinary SDK needs separate initialization.
import cloudinary
if CLOUDINARY_STORAGE.get("CLOUD_NAME"):
    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
        api_key=CLOUDINARY_STORAGE["API_KEY"],
        api_secret=CLOUDINARY_STORAGE["API_SECRET"],
        secure=True,
    )

# Use the modern STORAGES setting for Django 4.2+
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage"
        if IS_TESTING
        else ("cloudinary_storage.storage.MediaCloudinaryStorage" 
              if not DEBUG or CLOUDINARY_STORAGE.get("CLOUD_NAME") 
              else "django.core.files.storage.FileSystemStorage"),
    },
    "raw": {
        "BACKEND": "django.core.files.storage.FileSystemStorage"
        if IS_TESTING
        else ("cloudinary_storage.storage.RawMediaCloudinaryStorage"
              if not DEBUG or CLOUDINARY_STORAGE.get("CLOUD_NAME")
              else "django.core.files.storage.FileSystemStorage"),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# For backward compatibility and certain 3rd party apps
if IS_TESTING:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
elif not DEBUG or CLOUDINARY_STORAGE.get("CLOUD_NAME"):
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Trust the X-Forwarded-Proto header from Render's proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Brevo Email Settings
BREVO_API_KEY = os.environ.get("BREVO_API_KEY")
BREVO_SENDER_EMAIL = os.environ.get("BREVO_SENDER_EMAIL")

# Database Backup/Restore Upload Limits (50MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = None  
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
